# Generated by Django 2.2.4 on 2019-09-21 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('identification', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('first_lastname', models.CharField(max_length=30)),
                ('second_lastname', models.CharField(max_length=30)),
                ('role', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=7)),
                ('model', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='safecomappapi.Person')),
            ],
        ),
        migrations.CreateModel(
            name='RecordVisit',
            fields=[
                ('visit_id', models.AutoField(primary_key=True, serialize=False)),
                ('incoming_date', models.DateTimeField(auto_now_add=True)),
                ('outgoing_date', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(max_length=500)),
                ('plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='safecomappapi.Vehicle')),
                ('visit_identification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor', to='safecomappapi.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('blacklist_id', models.AutoField(primary_key=True, serialize=False)),
                ('plate', models.CharField(max_length=7)),
                ('reason', models.CharField(max_length=500)),
                ('visit_identification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_black', to='safecomappapi.Person')),
            ],
        ),
    ]
