# Generated by Django 2.2.4 on 2019-08-18 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safecomappapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=20)),
                ('first_lastname', models.CharField(max_length=30)),
                ('second_lastname', models.CharField(max_length=30)),
                ('role', models.BooleanField()),
            ],
        ),
    ]
