# Generated by Django 2.2.4 on 2019-10-05 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safecomappapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blacklist',
            name='plate',
        ),
    ]
