# Generated by Django 2.2.4 on 2019-09-22 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safecomappapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordvisit',
            name='visit_identification',
        ),
    ]
