# Generated by Django 2.2.4 on 2019-08-23 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safecomappapi', '0002_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_identification', models.CharField(max_length=12)),
                ('plate', models.CharField(max_length=7)),
                ('reason', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='RecordVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incoming_date', models.DateTimeField(auto_now_add=True)),
                ('outgoing', models.DateTimeField(blank=True, null=True)),
                ('plate', models.CharField(max_length=7)),
                ('visit_identification', models.CharField(max_length=12)),
                ('reason', models.CharField(max_length=500)),
            ],
        ),
    ]
