# Generated by Django 2.2.4 on 2019-10-05 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safecomappapi', '0002_remove_blacklist_plate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blacklist',
            old_name='visit_identification',
            new_name='visitor',
        ),
    ]
