# Generated by Django 2.2.4 on 2019-10-05 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safecomappapi', '0003_auto_20191005_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklist',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_black', to='safecomappapi.Person', unique=True),
        ),
    ]
