# Generated by Django 2.2.4 on 2019-08-28 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safecomappapi', '0003_blacklist_recordvisit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recordvisit',
            old_name='outgoing',
            new_name='outgoing_date',
        ),
        migrations.RemoveField(
            model_name='person',
            name='id',
        ),
        migrations.AlterField(
            model_name='person',
            name='identification',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
