# Generated by Django 2.2.4 on 2019-08-28 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safecomappapi', '0004_auto_20190827_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordvisit',
            name='visit_identification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safecomappapi.Person'),
        ),
    ]
